Add missing header after 2.3.0
keybinding.c:1713:4: error: use of undeclared identifier 'sigset_t'
                        sigset_t set;
                        ^
keybinding.c:1714:4: error: implicit declaration of function 'sigemptyset' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        sigemptyset(&set);
                        ^
keybinding.c:1714:17: error: use of undeclared identifier 'set'
                        sigemptyset(&set);
                                     ^
keybinding.c:1715:4: error: implicit declaration of function 'sigprocmask' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        sigprocmask(SIG_SETMASK, &set, NULL);
                        ^
keybinding.c:1715:16: error: use of undeclared identifier 'SIG_SETMASK'
                        sigprocmask(SIG_SETMASK, &set, NULL);
                                    ^
keybinding.c:1715:30: error: use of undeclared identifier 'set'
                        sigprocmask(SIG_SETMASK, &set, NULL);
                                                  ^